### Generate a response
GET {{baseUrl}}/ai/generate
Accept: application/json

### Generate a response stream
GET {{baseUrl}}/ai/generateStream
Accept: application/json

### RAG Ask
POST {{baseUrl}}/rag/ask
Content-Type: application/json

{
  "question": "List all price types, value and description"
}


### Google Example
POST {{googleUrl}}
X-goog-api-key: {{googleApiKey}}
Content-Type: application/json

{
    "contents": [
      {
        "parts": [
          {
            "text": "Explain how AI works in a few words"
          }
        ]
      }
    ]
  }
